name: 'Fastlane action test'
on: [push, repository_dispatch]

jobs:
  test_job:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
        ruby-version: [2.5.9, 2.6.8, 2.7.4, 3.0.2]
        verbose: [true, false]
    name: A job to test the GitHub fastlane action
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
    - name: Fastlane step (root directory)
      uses: maierj/fastlane-action@development
      with:
        lane: 'beta'
        options: '{ "option1": "value1", "option2": "value2" }'
        verbose: "${{ matrix.verbose}}"
      env:
        ENV_VARIABLE_1: VALUE_1
        ENV_VARIABLE_2: VALUE_2
    - name: Fastlane step (subdirectory)
      uses: maierj/fastlane-action@development
      with:
        lane: 'beta'
        subdirectory: 'ios'
        verbose: "${{ matrix.verbose}}"
      env:
        ENV_VARIABLE_1: VALUE_1
        ENV_VARIABLE_2: VALUE_2
    - name: Fastlane step (subdirectory + bundle-install-path)
      uses: maierj/fastlane-action@development
      with:
        lane: 'beta'
        subdirectory: 'ios'
        bundle-install-path: 'vendor/bundle'
        verbose: "${{ matrix.verbose}}"
      env:
        ENV_VARIABLE_1: VALUE_1
        ENV_VARIABLE_2: VALUE_2
